/**
 * Describe: 路由Constants
 */
export class Routes {
  static readonly MAIN_PAGE = 'mainPage' //主页面
  static readonly SPLASH_PAGE = 'splashPage' //启动页面
  static readonly LOGIN_VIEW = 'loginView' //登录页面
  static readonly HOME_VIEW = 'homeView' //首页
  static readonly MINE_VIEW = 'mineView' //我的页面
  static readonly MINE_LIKE_VIEW = 'meLikeView' //我的喜欢页面
  static readonly MINE_FOCUS_VIEW = 'MINE_FOCUS_VIEW' //关注页面
  static readonly MINE_COLLECTION_VIEW = 'MINE_COLLECTION_VIEW' //收藏页面
  static readonly MINE_SETTING_VIEW = 'MINE_SETTING_VIEW' //设置页面
}
